// Generated by EmDash CLI
// Do not edit manually - run `emdash types` to regenerate

import type { PortableTextBlock } from "emdash";

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  content?: PortableTextBlock[];
  featured?: boolean;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  content?: PortableTextBlock[];
  project_status?: string;
  url?: string;
  github?: string;
  featured?: boolean;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Home {
  id: string;
  slug: string | null;
  status: string;
  eyebrow?: string;
  title: string;
  description: string;
  highlights_title: string;
  highlights_description?: string;
  posts_title: string;
  posts_description?: string;
  projects_title: string;
  projects_description?: string;
  newsletter_cta_label: string;
  newsletter_cta_href: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface HomeHighlight {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  icon_key: "database" | "workflow" | "search" | "mail";
  sort_order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ListingHeader {
  id: string;
  slug: string | null;
  status: string;
  posts_label?: string;
  posts_icon?: "posts" | "projects" | "book" | "briefcase" | "file" | "folder" | "code" | "lightbulb";
  projects_label?: string;
  projects_icon?: "posts" | "projects" | "book" | "briefcase" | "file" | "folder" | "code" | "lightbulb";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface NewsletterPage {
  id: string;
  slug: string | null;
  status: string;
  eyebrow?: string;
  title: string;
  description: string;
  signup_title: string;
  signup_description: string;
  name_label: string;
  name_optional_label?: string;
  name_placeholder?: string;
  email_label: string;
  email_placeholder?: string;
  email_help?: string;
  submit_label: string;
  submitting_label: string;
  consent_copy: string;
  success_title: string;
  success_message: string;
  disabled_heading: string;
  disabled_body: string;
  expectations_title: string;
  expectation_one_title: string;
  expectation_one_description: string;
  expectation_two_title: string;
  expectation_two_description: string;
  expectation_three_title: string;
  expectation_three_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface NavigationIcon {
  id: string;
  slug: string | null;
  status: string;
  page: string;
  icon_key: "page" | "book" | "user" | "briefcase" | "compass" | "link" | "file" | "folder" | "calendar" | "heart" | "star" | "lightbulb" | "globe" | "code" | "camera" | "music" | "message" | "settings";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}