/**
 * Deterministic EmDash type-artifact generator.
 *
 * Derives `.emdash/types.ts` and `.emdash/schema.json` directly from the
 * declared `.emdash/seed.json` — no running server, login, token, or database
 * reset required. The output is byte-identical to what `emdash types` writes
 * after applying this seed to an empty database, because it reuses EmDash's
 * own generator (`generateTypeScript`, `uniqueInterfaceNames`) and schema
 * hash (`hashString`) with the same field mapping `applySeed` persists.
 *
 * The type-generation functions are internal to the emdash package (not on
 * its public export map), so they are loaded from the versioned dist chunk.
 * If the emdash dependency is upgraded and the chunk can no longer be found,
 * this script fails loudly instead of generating divergent types.
 */

import { readdir, writeFile } from "node:fs/promises";
import { hashString, validateSeed } from "emdash";
import type { SeedCollection, SeedField, SeedFile } from "emdash/seed";

const distDir = new URL("../node_modules/emdash/dist/", import.meta.url);

interface TypeGenerator {
  generateTypeScript(collection: unknown, interfaceName?: string): string;
  uniqueInterfaceNames(collections: unknown[]): Map<string, string>;
}

async function loadEmDashTypeGenerator(): Promise<TypeGenerator> {
  const entries = await readdir(distDir);
  const chunk = entries.find((name) => /^zod-generator-.+\.mjs$/.test(name));
  if (!chunk) {
    throw new Error(
      "Could not locate EmDash's internal zod-generator chunk in node_modules/emdash/dist. The emdash package layout changed; update scripts/generate-types.ts to match.",
    );
  }
  const mod = (await import(new URL(chunk, distDir).href)) as Record<string, unknown>;
  // The chunk minifies its exports to single-letter aliases (t/r in 0.32);
  // resolve by function identity rather than name.
  const findFn = (fnName: string): unknown =>
    Object.values(mod).find((value) => typeof value === "function" && value.name === fnName);
  const generateTypeScript = findFn("generateTypeScript");
  const uniqueInterfaceNames = findFn("uniqueInterfaceNames");
  if (typeof generateTypeScript !== "function" || typeof uniqueInterfaceNames !== "function") {
    throw new Error(`EmDash chunk ${chunk} no longer exports generateTypeScript/uniqueInterfaceNames.`);
  }
  return {
    generateTypeScript: generateTypeScript as TypeGenerator["generateTypeScript"],
    uniqueInterfaceNames: uniqueInterfaceNames as TypeGenerator["uniqueInterfaceNames"],
  };
}

/**
 * Mirror of how `applySeed` persists seed fields into `_emdash_fields`
 * (see applySeed in emdash) combined with the `/schema` export projection
 * (slug, label, type, required, unique, defaultValue, validation, widget,
 * options). Undefined values are dropped by JSON serialization exactly as
 * the server route does.
 */
function toStoredField(field: SeedField) {
  return {
    slug: field.slug,
    label: field.label,
    type: field.type,
    required: field.required || false,
    unique: field.unique || false,
    defaultValue: field.defaultValue,
    validation: field.validation,
    widget: field.widget,
    options: field.options,
  };
}

/** Mirror of the `/schema` collection projection. */
function toSchemaExportCollection(collection: SeedCollection) {
  return {
    slug: collection.slug,
    label: collection.label,
    labelSingular: collection.labelSingular,
    description: collection.description,
    icon: collection.icon,
    supports: collection.supports || [],
    fields: collection.fields.map(toStoredField),
  };
}

const seedFile = Bun.file(new URL("../.emdash/seed.json", import.meta.url));
const seed = (await seedFile.json()) as SeedFile;

const validation = validateSeed(seed);
if (!validation.valid) {
  console.error("Refusing to generate types from an invalid seed:");
  for (const error of validation.errors) {
    console.error(typeof error === "string" ? error : JSON.stringify(error));
  }
  process.exit(1);
}

if (!seed.collections?.length) {
  console.error("Seed declares no collections; nothing to generate.");
  process.exit(1);
}

const generator = await loadEmDashTypeGenerator();

// Same shape the /schema endpoint feeds its generators: collections with fields.
const collectionsWithFields = seed.collections.map(toSchemaExportCollection);

// Schema snapshot + version hash, identical to GET /schema.
const schemaExportWithoutVersion = JSON.stringify({ collections: collectionsWithFields });
const schema = {
  ...JSON.parse(schemaExportWithoutVersion),
  version: await hashString(schemaExportWithoutVersion),
};

// Types file, identical to GET /schema?format=typescript (via `emdash types`).
const interfaceNames = generator.uniqueInterfaceNames(collectionsWithFields);
const header =
  "// Generated by EmDash CLI\n// Do not edit manually - run `emdash types` to regenerate\n\nimport type { PortableTextBlock } from \"emdash\";\n\n";
const types = `${header}${collectionsWithFields
  .map((collection) => generator.generateTypeScript(collection, interfaceNames.get(collection.slug)))
  .join("\n\n")}`;

await writeFile(new URL("../.emdash/types.ts", import.meta.url), types, "utf-8");
await writeFile(
  new URL("../.emdash/schema.json", import.meta.url),
  JSON.stringify(schema, null, 2),
  "utf-8",
);

console.log(
  `Generated .emdash/types.ts and .emdash/schema.json from .emdash/seed.json (${collectionsWithFields.length} collections, schema version ${schema.version}).`,
);
